### ISSUE TITLE
Windows Defender accuses of malware

### ISSUE THREAD

**Issue by pedrovanzella** [HouseBreaker/Shameless#14]
When I tried to open Shameless on Windows 10, I got a prompt from Windows Defender, saying that it found a "malicious file". It then proceeded to delete the shameless.exe file.

**Comment by HouseBreaker** [comment]
lmao what the fuck

**Comment by HouseBreaker** [comment]
There isn't any malicious code inside Shameless, you can get anyone who knows anything about code to check out the source code which is on this github page and which Shameless is compiled from.

I assume it catches it because it uses the internet and also writes to your hard disk.

Then again, 80% of programs do that as well.

**Comment by rourke** [comment]
I've just got the same error:

![image](https://cloud.githubusercontent.com/assets/2820753/15793741/574997de-29e6-11e6-8af7-2cfcc290d6ff.png)

However I know it's bullshit, so I just allowed it.

**Comment by HouseBreaker** [comment]
A quick google search shows a similar software on GitHub gets flagged as this exact trojan, as there are GitHub issues dedicated to this on other repositories. I don't know what to do in this case to solve it. Maybe it'll go away when I release another update.

Until then, if anyone has doubts that this software does anything malicious, they're free to analyze the source code which is available here.

Thanks for bringing this to my attention.
